server:
   port: 9000
spring:
   datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: ''
   h2:
      console:
         enabled: true
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
         ddl-auto: update
      show-sql: true
   config:
      import:
      - application_qa.yml
      - application_prod.yml
   profiles:
      active:
      - qa

build:
   version: '3.0'

cards:
   message: Welcome to ashu tiwary cards api
   contactDetails:
      name: Ashu Tiwary cards
      email: ashu.tiwary19-cards@gmail.com
   onCallSupport:
   - (444) 444-1234
   - (555) 555-1434