services:
   network-deploy-service:
      networks:
      - ashutiwarynet
   microservice-base-config:
      extends:
         service: network-deploy-service
#   environment:
#     SPRING_PROFILES_ACTIVE: default
      deploy:
         resources:
            limits:
               memory: 700m
   microservice-configserver-config:
      extends:
         service: microservice-base-config
      environment:
         SPRING_PROFILES_ACTIVE: default
         SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/