server:
  port: 9000
spring:
  application:
    name: cards
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/ms-udemy-bank
    username: root
    password: password
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: optional:configserver:http://localhost:8071/

# to expose all actuator management api
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    com:
      ashu:
        cards: DEBUG
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"
